kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: todel-dev-pipeline-claim
  namespace: todel-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
status:

